import java.io.Serializable;
import java.util.*;

public class PlanException extends Exception implements Serializable {
    private int id;

//    private static ArrayList<Integer> uniqueIds = new ArrayList<Integer>();

    public PlanException() {
        this.id = generateRandomId();
    }

    public int getNewId() {
        return id;
    }

    //    public static int generateRandomId() {
//        Random random = new Random();
//        int randomId = random.nextInt(3000000, 3999999);
//        for (int id : uniqueIds) {
//            if (randomId == id) {
//                randomId = generateRandomId();
//            } else {
//                uniqueIds.add(randomId);
//            }
//        }
//        return randomId;
//    }
    public static int generateRandomId() {
        Random random = new Random();
        int randomId = random.nextInt(3000000, 3999999);
        return randomId;
    }


    @Override
    public String toString() {
        return "The Plan ID was not valid and a new ID " + id + " is generated by admin and assigned for the Plan";
    }
}
