
import java.awt.Color;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author 98990
 */
public class UpdateUI extends javax.swing.JFrame {

    /**
     * Creates new form UpdateUI
     */
    MobilePlan plan;
    UserUI userUI;
    AdminUI adminUI;

    public UpdateUI(MobilePlan plan, UserUI userUI) {
        this.plan = plan;
        this.userUI = userUI;
        initComponents();

        osTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel(MobileType.values()));
        planidTextField.setText(plan.getId() + "");
        planidTextField.setEditable(false);
        planidTextField.setBackground(Color.gray);
        usernameTextField.setText(plan.getUsername());
        modelTextField.setText(plan.getHandsetModel());
        memorySizeTextField.setText(plan.handset.getMemorySize() + "");
        priceTextField.setText(plan.getHandsetPrice() + "");
        internetQoutaTextField.setText(plan.internetQuota + "");
        capLimitTextField.setText(plan.capLimit + "");
        dayTextField.setText(plan.getExpiryDate().getDay() + "");
        monthTextField.setText(plan.getExpiryDate().getMonth() + "");
        yearTextField.setText(plan.getExpiryDate().getYear() + "");
        if (plan instanceof PersonalPlan) {
            personalRadioButton.setSelected(true);
            businessRadioButton.setSelected(false);
            personalRadioButton.setEnabled(false);
            businessRadioButton.setEnabled(false);
            cityAbnLabel.setText("City");
            cityABNTextField.setText(((PersonalPlan) plan).city);
            numEmployeeTextField.setText("");
            noEmployeeLabel.setVisible(false);
            numEmployeeTextField.setVisible(false);
        } else {
            personalRadioButton.setSelected(false);
            personalRadioButton.setEnabled(false);
            businessRadioButton.setSelected(true);
            businessRadioButton.setEnabled(false);
            cityAbnLabel.setText("ABN");
            cityABNTextField.setText(((BusinessPlan) plan).ABN + "");
            numEmployeeTextField.setText(((BusinessPlan) plan).numberOfEmployees + "");
            noEmployeeLabel.setVisible(true);
            numEmployeeTextField.setVisible(true);
        }
    }

    public UpdateUI(MobilePlan plan, AdminUI adminUI) {
        this.plan = plan;
        this.adminUI = adminUI;

        initComponents();
        osTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel(MobileType.values()));
        planidTextField.setText(plan.getId() + "");
        planidTextField.setEditable(false);
        planidTextField.setBackground(Color.gray);
        usernameTextField.setText(plan.getUsername());
        modelTextField.setText(plan.getHandsetModel());
        memorySizeTextField.setText(plan.handset.getMemorySize() + "");
        priceTextField.setText(plan.getHandsetPrice() + "");
        internetQoutaTextField.setText(plan.internetQuota + "");
        capLimitTextField.setText(plan.capLimit + "");
        dayTextField.setText(plan.getExpiryDate().getDay() + "");
        monthTextField.setText(plan.getExpiryDate().getMonth() + "");
        yearTextField.setText(plan.getExpiryDate().getYear() + "");
        if (plan instanceof PersonalPlan) {
            personalRadioButton.setSelected(true);
            businessRadioButton.setSelected(false);
            personalRadioButton.setEnabled(false);
            businessRadioButton.setEnabled(false);
            cityAbnLabel.setText("City");
            cityABNTextField.setText(((PersonalPlan) plan).city);
            numEmployeeTextField.setText("");
            noEmployeeLabel.setVisible(false);
            numEmployeeTextField.setVisible(false);
        } else {
            personalRadioButton.setSelected(false);
            personalRadioButton.setEnabled(false);
            businessRadioButton.setSelected(true);
            businessRadioButton.setEnabled(false);
            cityAbnLabel.setText("ABN");
            cityABNTextField.setText(((BusinessPlan) plan).ABN + "");
            numEmployeeTextField.setText(((BusinessPlan) plan).numberOfEmployees + "");
            noEmployeeLabel.setVisible(true);
            numEmployeeTextField.setVisible(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        personalRadioButton = new javax.swing.JRadioButton();
        businessRadioButton = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        cityAbnLabel = new javax.swing.JLabel();
        noEmployeeLabel = new javax.swing.JLabel();
        planidTextField = new javax.swing.JTextField();
        usernameTextField = new javax.swing.JTextField();
        modelTextField = new javax.swing.JTextField();
        memorySizeTextField = new javax.swing.JTextField();
        priceTextField = new javax.swing.JTextField();
        internetQoutaTextField = new javax.swing.JTextField();
        capLimitTextField = new javax.swing.JTextField();
        dayTextField = new javax.swing.JTextField();
        monthTextField = new javax.swing.JTextField();
        yearTextField = new javax.swing.JTextField();
        cityABNTextField = new javax.swing.JTextField();
        numEmployeeTextField = new javax.swing.JTextField();
        clearButton = new javax.swing.JButton();
        updateButton = new javax.swing.JButton();
        osTypeComboBox = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        personalRadioButton.setText("Personal Plan");

        businessRadioButton.setText("Business Plan");

        jLabel1.setText("Plan ID");

        jLabel2.setText("Username");

        jLabel3.setText("Mobile Phone _______________________________________________________________");

        jLabel4.setText("Model");

        jLabel5.setText("OS Type");

        jLabel6.setText("Memory Size");

        jLabel7.setText("Price");

        jLabel8.setText("Internet Quota");

        jLabel9.setText("Cap Limit");

        jLabel10.setText("EXP Date ______________________________________________________________________");

        jLabel11.setText("Day");

        jLabel12.setText("Month");

        jLabel13.setText("Year");

        cityAbnLabel.setText("City");

        noEmployeeLabel.setText("NO. Employees");

        memorySizeTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                memorySizeTextFieldActionPerformed(evt);
            }
        });

        clearButton.setText("CLEAR");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        updateButton.setText("UPDATE");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        osTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(personalRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(businessRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(planidTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                                    .addComponent(usernameTextField))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(clearButton, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(updateButton, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(16, 16, 16))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 12, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel9)
                                            .addComponent(jLabel11)
                                            .addComponent(jLabel12)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(cityAbnLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addComponent(noEmployeeLabel))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(24, 24, 24)
                                                .addComponent(memorySizeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGap(24, 24, 24)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(priceTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(internetQoutaTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(capLimitTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(monthTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                    .addGap(26, 26, 26)
                                                    .addComponent(dayTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(26, 26, 26)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(yearTextField)
                                                    .addComponent(cityABNTextField)
                                                    .addComponent(numEmployeeTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(24, 24, 24)
                                                .addComponent(osTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(24, 24, 24)
                                        .addComponent(modelTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(167, 167, 167)))))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(personalRadioButton)
                            .addComponent(businessRadioButton))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(planidTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(clearButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(usernameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(updateButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4))
                    .addComponent(modelTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(osTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(memorySizeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(priceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(internetQoutaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(capLimitTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(dayTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(monthTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(yearTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cityAbnLabel)
                    .addComponent(cityABNTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(noEmployeeLabel)
                    .addComponent(numEmployeeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void memorySizeTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_memorySizeTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_memorySizeTextFieldActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        // TODO add your handling code here:
        try {
            String username = usernameTextField.getText();
            String model = modelTextField.getText();
            MobileType type = (MobileType) osTypeComboBox.getSelectedItem();
            int size = Integer.parseInt(memorySizeTextField.getText());
            double price = Double.parseDouble(priceTextField.getText());
            int quota = Integer.parseInt(internetQoutaTextField.getText());
            int cap = Integer.parseInt(capLimitTextField.getText());
            int day = Integer.parseInt(dayTextField.getText());
            int month = Integer.parseInt(monthTextField.getText());
            int year = Integer.parseInt(yearTextField.getText());
            MyDate date = new MyDate(year, month, day);
            MobilePhone phone = new MobilePhone(model, type, size, price);
            plan.setUsername(username);
            plan.setCapLimit(cap);
            plan.setExpiryDate(date);
            plan.setHandset(phone);
            plan.setInternetQuota(quota);
            if (personalRadioButton.isSelected()) {
                String city = cityABNTextField.getText();
                ((PersonalPlan) plan).city = city;
            } else {
                int abn = Integer.parseInt(cityABNTextField.getText());
                int numEmployees = Integer.parseInt(numEmployeeTextField.getText());
                ((BusinessPlan) plan).ABN = abn;
                ((BusinessPlan) plan).numberOfEmployees = numEmployees;
            }
            JOptionPane.showMessageDialog(this, "Plan has been updated");
            if (adminUI != null) {
                adminUI.fillTable();
            } else {
                userUI.fillTable();
            }
            this.dispose();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }//GEN-LAST:event_updateButtonActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        // TODO add your handling code here:
        osTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel(MobileType.values()));
        planidTextField.setText(plan.getId() + "");
        planidTextField.setEditable(false);
        planidTextField.setBackground(Color.gray);
        usernameTextField.setText(plan.getUsername());
        modelTextField.setText(plan.getHandsetModel());
        memorySizeTextField.setText(plan.handset.getMemorySize() + "");
        priceTextField.setText(plan.getHandsetPrice() + "");
        internetQoutaTextField.setText(plan.internetQuota + "");
        capLimitTextField.setText(plan.capLimit + "");
        dayTextField.setText(plan.getExpiryDate().getDay() + "");
        monthTextField.setText(plan.getExpiryDate().getMonth() + "");
        yearTextField.setText(plan.getExpiryDate().getYear() + "");
        if (plan instanceof PersonalPlan) {
            personalRadioButton.setSelected(true);
            businessRadioButton.setSelected(false);
            personalRadioButton.setEnabled(false);
            businessRadioButton.setEnabled(false);
            cityAbnLabel.setText("City");
            cityABNTextField.setText(((PersonalPlan) plan).city);
            numEmployeeTextField.setText("");
            noEmployeeLabel.setVisible(false);
            numEmployeeTextField.setVisible(false);
        } else {
            personalRadioButton.setSelected(false);
            personalRadioButton.setEnabled(false);
            businessRadioButton.setSelected(true);
            businessRadioButton.setEnabled(false);
            cityAbnLabel.setText("ABN");
            cityABNTextField.setText(((BusinessPlan) plan).ABN + "");
            numEmployeeTextField.setText(((BusinessPlan) plan).numberOfEmployees + "");
            noEmployeeLabel.setVisible(true);
            numEmployeeTextField.setVisible(true);
        }
    }//GEN-LAST:event_clearButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new UpdateUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton businessRadioButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField capLimitTextField;
    private javax.swing.JTextField cityABNTextField;
    private javax.swing.JLabel cityAbnLabel;
    private javax.swing.JButton clearButton;
    private javax.swing.JTextField dayTextField;
    private javax.swing.JTextField internetQoutaTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField memorySizeTextField;
    private javax.swing.JTextField modelTextField;
    private javax.swing.JTextField monthTextField;
    private javax.swing.JLabel noEmployeeLabel;
    private javax.swing.JTextField numEmployeeTextField;
    private javax.swing.JComboBox<String> osTypeComboBox;
    private javax.swing.JRadioButton personalRadioButton;
    private javax.swing.JTextField planidTextField;
    private javax.swing.JTextField priceTextField;
    private javax.swing.JButton updateButton;
    private javax.swing.JTextField usernameTextField;
    private javax.swing.JTextField yearTextField;
    // End of variables declaration//GEN-END:variables
}
